apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-server
    component: service
  name: product-server
  namespace: ks-shop-dev
spec:
  ports:
    - name: http
      port: 8041
      protocol: TCP
      targetPort: 8041
  selector:
    app: product-server
    component: service
    tier: backend
  sessionAffinity: None
